let callbacks = {
    MESSAGE_CREATECallback: null,
    MESSAGE_DELETECallback: null,
    MESSAGE_UPDATECallback: null,
    CHANNEL_CREATECallback: null,
    CHANNEL_DELETECallback: null,
    WEBHOOKS_UPDATECallback: null,
    VOICE_SERVER_UPDATECallback: null,
    VOICE_STATE_UPDATECallback: null,
    USER_UPDATECallback: null,
    TYPING_STARTCallback: null,
    STAGE_INSTANCE_UPDATECallback: null,
    STAGE_INSTANCE_DELETECallback: null,
    STAGE_INSTANCE_CREATECallback: null,
    PRESENCE_UPDATECallback: null,
    MESSAGE_REACTION_ADDCallback: null,
    GUILD_ROLE_CREATECallback: null,
    GUILD_ROLE_DELETECallback: null,
    MESSAGE_REACTION_REMOVE_EMOJICallback: null,
    MESSAGE_REACTION_REMOVE_ALLCallback: null,
    MESSAGE_REACTION_REMOVECallback: null,
    MESSAGE_REACTION_ADDCallback: null,
    MESSAGE_DELETE_BULKCallback: null,
    INVITE_DELETECallback: null,
    INVITE_CREATECallback: null,
    INTERACTION_CREATECallback: null,
    INTEGRATION_DELETECallback: null,
    INTEGRATION_CREATECallback: null,
    INTEGRATION_UPDATECallback: null,
    GUILD_ROLE_UPDATECallback: null,
    GUILD_MEMBERS_CHUNKCallback: null,
    GUILD_MEMBER_UPDATECallback: null,
    GUILD_MEMBER_REMOVECallback: null,
    GUILD_MEMBER_ADDCallback: null,
    GUILD_INTEGRATIONS_UPDATECallback: null,
    GUILD_STICKERS_UPDATECallback: null,
    GUILD_EMOJIS_UPDATECallback: null,
    GUILD_BAN_REMOVECallback: null,
    GUILD_BAN_ADDCallback: null,
    GUILD_DELETECallback: null,
    GUILD_UPDATECallback: null,
    GUILD_CREATECallback: null,
    THREAD_MEMBERS_UPDATECallback: null,
    THREAD_MEMBER_UPDATECallback: null,
    THREAD_LIST_SYNCCallback: null,
    THREAD_DELETECallback: null,
    THREAD_UPDATECallback: null,
    THREAD_CREATECallback: null,
    CHANNEL_PINS_UPDATECallback: null,
    CHANNEL_UPDATECallback: null,
    INVALID_SESSIONCallback: null,
    RECONNECTCallback: null,
    RESUMEDCallback: null,
    READYCallback: null,
    HELLOCallback: null,
}

module.exports = { 
    callbacks
}